genome_dir:
    "../../test/"
base_name:
    "sulfolobus"
num_threads:
    "36"
Group_to_cluster:
    "0"
alpha:
    0.05
prodigal_path:
    "/usr/bin/prodigal"
mmseqs_path:
    "$HOME/miniconda3/envs/PopCOGenT/bin/mmseqs"
muscle_path:
    "muscle"
